### ISSUE TITLE
ajaxform component doesn't work with select or textarea elements

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1006]
And potentially other form elements I'm not thinking of right now.

Related: #570 (fixed via #1001)

**Comment by toolness** [comment]
Uh, wait, is this actually true?  The ajaxform in the style guide had a `<select>` in it for a long time, and it worked fine.

I'm only just realizing now that #1001 broke it, because the ajaxform is now throwing an error complaining about the `<select>` instead of treating it like a regular input...  Is there something special about the way `<select>` works that made you think the ajaxform wouldn't deal properly with it?

Similar with textarea actually... although we don't have a `<textarea>` in an ajaxform anywhere on the site, I don't think there's actually anything about that field that would make it work any differently (from ajaxform's perspective) from a standard input widget.

**Comment by jseppi** [comment]
Oh shoot, you are right, my bad. Want to remove those offending lines?

**Comment by toolness** [comment]
Sure will file a PR soon!

**Comment by jseppi** [comment]
sorry :(
