### ISSUE TITLE
Style Guide regressions/rot

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1115]
Looks like we have some issues with our Style Guide being out of date with recent CSS and DOM structure changes. Also maybe some content needs updating (like the bit about using Skeleton). Should probably keep the guide up-to-date!

Here are some quick screenshots of things that look weird:

<img width="319" alt="screen shot 2016-12-14 at 2 28 29 pm" src="https://cloud.githubusercontent.com/assets/697848/21199596/c779da6c-c209-11e6-9cc6-05b3fd438810.png">

<img width="234" alt="screen shot 2016-12-14 at 2 28 23 pm" src="https://cloud.githubusercontent.com/assets/697848/21199589/becb2268-c209-11e6-9d57-3bd7e4f173f6.png">

<img width="698" alt="screen shot 2016-12-14 at 2 28 36 pm" src="https://cloud.githubusercontent.com/assets/697848/21199609/d14f399c-c209-11e6-8654-6dfbb374f517.png">

<img width="922" alt="screen shot 2016-12-14 at 2 28 50 pm" src="https://cloud.githubusercontent.com/assets/697848/21199638/f6fec89c-c209-11e6-88a2-28b0e8bf0d9a.png">

<img width="506" alt="screen shot 2016-12-14 at 2 29 05 pm" src="https://cloud.githubusercontent.com/assets/697848/21199644/fe16a1b8-c209-11e6-8d22-274d4656d95e.png">

**Comment by ericronne** [comment]
tagging myself to follow this issue!

**Comment by toolness** [comment]
Oops, I'm re-opening this because #1128 didn't actually fix everything. Specifically, tasks remaining include:

- [ ] Fix the [2 rows have errors](https://cloud.githubusercontent.com/assets/697848/21199638/f6fec89c-c209-11e6-88a2-28b0e8bf0d9a.png) alert.
- [ ] Fix the [forms example](https://cloud.githubusercontent.com/assets/697848/21199644/fe16a1b8-c209-11e6-8d22-274d4656d95e.png).
