### ISSUE TITLE
Figure out how to stop missing static files from breaking everything

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1136]
As documented in #1129, a missing JS file (one that had been deleted) referenced in a template (`step_4.html`) caused Whitenoise to bomb and thus a `500` error was issued. This is terrible. We either need to figure out a test to make sure that won't happen, or figure how to disable or capture that kind of Whitenoise exception.

**Comment by jseppi** [comment]
I can't figure out how to not have this happen. @toolness?

**Comment by jseppi** [comment]
Whitenoise docs say to check Django staticfiles: http://whitenoise.evans.io/en/stable/django.html#troubleshooting-the-whitenoise-storage-backend

**Comment by jseppi** [comment]
Would running tests not in DEBUG mode have caught this?

**Comment by toolness** [comment]
Hmm, so the really weird thing is that we added `frontend.tests.test_collectstatic` in #776 *specifically* to address this exact situation, because it had bitten us in the past in #772.  So I'm not sure why it didn't catch this problem. Looking into it now!

**Comment by toolness** [comment]
Oh geez. Yeah, so I guess that `test_collectstatic` wasn't exploding because `manage.py collectstatic` was working fine, it was a template *requesting* a static file that didn't exist that made things explode.

Blergh.

I guess we should be running the tests without `DEBUG` enabled, though it's a bit of a tradeoff because I think there may be some sanity assertions in the code that are only run if `DEBUG` is actually present? I'm not sure... will look into it.

**Comment by toolness** [comment]
But yeah, I don't think it's actually whitenoise that's breaking everything, as much as I want to blame it. 😛  It's delegating most of its behavior to Django's [`ManifestStaticFilesStorage `](https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/#manifeststaticfilesstorage), I think, and that's the one that's raising the exceptions.

Imma fix this up somehow.
