### ISSUE TITLE
Make SECURE_PROXY_SSL_HEADER, USE_X_FORWARDED_HOST configurable via environment

### ISSUE THREAD

**Issue by toolness** [18F/calc#1188]
As mentioned in #1187, currently these are hard-coded into our app, but this then makes our app potentially behave oddly (or worse, have vulnerabilities) when not deployed on the exact same infrastructure that we're targeting.

**Comment by jseppi** [comment]
As I mentioned in Slack, I'm pretty sure `USE_X_FORWARDED_HOST` is actually not needed because CloudFront can be configured (and has been for us) to set the actual `Host` header, not `X-Forwarded-Host`.

Ref: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html
