### ISSUE TITLE
SIN numbers shouldn't break on hyphens

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1203]
This looks funky and is hard to read
<img width="247" alt="screen shot 2017-01-04 at 5 45 49 pm" src="https://cloud.githubusercontent.com/assets/509309/21664730/aa139ca4-d2a5-11e6-9bfc-72b325825536.png">

**Comment by jseppi** [comment]
heh, interesting. Looks like two ways to accomplish [not-breaking-on-hyphens](https://css-tricks.com/forums/topic/prevent-word-breaks/):

1. use a "non-breaking-hyphen" character: `&​#8209;`, which isn't doable for us without doing some kind of string replacement (like in JS or in responses from the API)
1. use the css rule `white-space: nowrap`, but if a SIN column has multiple numbers, I think it would make the whole cell be a single line instead of wrapping anywhere :\

**Comment by toolness** [comment]
Oh, this is happening on data capture stuff only, right?  Since we don't currently show SIN numbers in the data explorer, I think?

**Comment by hbillings** [comment]
yep! Not the explorer, but the admin pages and the data capture pages. Tagged accordingly. :)

**Comment by toolness** [comment]
In #1938, I added an `unbroken_hyphenize` function that does the string replacement Seppi suggested above, if that's useful.
