### ISSUE TITLE
Deployment - Prod URL seems to serve cached version of index page, resulting in 404s for css and js files

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1257]
<img width="404" alt="screen shot 2017-01-18 at 2 12 13 pm" src="https://cloud.githubusercontent.com/assets/697848/22082116/13604d1a-dd8c-11e6-9203-015a4eb462b5.png">

During today's production deployment, I noticed that after the deployment finished, when I refreshed https://calc.gsa.gov, which I already had open, I got an unstyled front page. I noticed that the front page was still referencing the previous static files (as shown in the above image). However, when I viewed the page in another browser, everything worked as expected. Also if I changed the URL by adding a query string (https://calc.gsa.gov?whatever), then I received the new version with correct static files.

I think this has to do with caching with CloudFront, but I guess it could also be something weird in Chrome, or maybe just cache headers in general.

I'm not quite sure how to determine the cause or debug at this point.

**Comment by jseppi** [comment]
Potentially a trail...the `x-cache` header:

<img width="479" alt="screen shot 2017-01-18 at 3 14 07 pm" src="https://cloud.githubusercontent.com/assets/697848/22083271/ddb702da-dd90-11e6-9eb0-125ff4fd666c.png">

**Comment by jseppi** [comment]
So the problem is the the `index.html` I was getting was the old one, which was referencing now-non-existent CSS and JS assets (which have unique filenames due to the `CompressedManifestStaticFilesStorage` middleware). I am fairly sure I was getting the old `index.html` because the new one had not yet reached whatever CloudFront edge node I was being served from.

Here are some potential mitigations:
1. Leave `calc-prod-venerable` up long enough for all the CloudFront edges to get updated before deleting it. This might not actually work because maybe leaving it up means it never fully clears out of CloudFront since traffic will keep going to it.
1. Stop using `CompressedManifestStaticFilesStorage` so that our asset filenames are always good. This will only work on deploys that don't include new references to assets. If the old index.html references `now-deleted-file.css` and a user is still getting index.html they'll get a 404 on that old css file.

Any other ideas, @toolness?

**Comment by jseppi** [comment]
Uh, I guess we could only do prod deploys in the middle of the night so that nobody is impacted. I think that is the worst option though.

**Comment by toolness** [comment]
Oh blug.

I'd advise against option 2 (stopping the use of `CompressedManifestStaticFilesStorage`) because hashing the file names to "version" them is actually a [best practice](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ReplacingObjects.html).  The problem that un-hashing them opens up is that it then becomes completely ambiguous what version each static asset has--for instance, the vendor JS bundle could be coming from the old deployment (because the request hits edge node X) while the browserified JS bundle could be coming from the new deployment (because the request hits edge node Y), resulting in a JS runtime exception.  In other words it results in a *more* complicated situation than what we have now, where it's just the contents of `index.html` that's uncertain--instead, *every* static asset will be uncertain!

Here are some other potential options:

1. [Invalidate `index.html` when we deploy a new version](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html)?  I'm not sure how long it takes for the invalidation to take place, though.

2. Never cache `index.html`!?  According to a [caching-related Stack Overflow post](http://stackoverflow.com/a/18779381), It looks like this is a combination of setting the `no-cache` header on our end, and setting the CF distribution's `Minimum TTL` to 0.

3. Copy our static assets to a S3 bucket and link to them at that location.  This means that if we have `https://static.calc.gsa.gov/foo.min.2359035.js` in the old version and `https://static.calc.gsa.gov/foo.min.ffffbcd.js` in the new version, both links will still work because we're just *copying* the static assets over on each deploy, leaving the old versions still lying around in case stale `index.html`s want to access them.  This would only fix 404s occurring because of static asset retrieval; any other 404's that might be occurring would still be occurring. Blah.

I wish I knew more about CloudFront.  Blah.

**Comment by toolness** [comment]
Oh, I just saw a webinar.

Around [17:00 in the CloudFront webinar](https://youtu.be/s9Xt1qzD6SA?t=17m) they discuss setting extremely low TTLs (even 0 seconds) for dynamic content such as our `index.html`, so it doesn't seem like an unusual thing to do at all.

Is it possible to just set a TTL of 0 for anything that isn't under `/static/` for now?

Another thing is that because we're showing the user's email address on every page if they're logged in, we want to make sure that CloudFront isn't somehow caching that globally for the general public.  This was actually the case at my old job, where a donations page pre-filled a form's contents with the contact info for a random person who had recently filled it out!

**Comment by jseppi** [comment]
Oh awesome, thanks for looking into this stuff! Let's see what they can do for us in #cloud-gov-support!

**Comment by toolness** [comment]
Woot!

Actually I just saw another video--well, part of one, it's a series of lightning talks.  The [lightning talk starting at 13:30](https://youtu.be/fgbJJ412qRE?t=13m30s) is all about caching and is REALLY good (and only like 10 mins).  It actually looks like we might be able to do this without changing our CloudFront configuration *at all*--because CF uses `Cache-Control` headers if we supply them and defaults to its hyper-aggressive defaults if we don't, I think that we might be able to fix this from our end by just providing the right headers upstream to CF.  And we can potentially simulate it locally too, by addressing #1259.

Anyhow that's just my current guess.

**Comment by jseppi** [comment]
app-level changes would absolutely be ideal

**Comment by jseppi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, when a new deployment occurs, I should not get cache-related 404 errors.](https://trello.com/c/psQWSayd/217-as-a-user-when-a-new-deployment-occurs-i-should-not-get-cache-related-404-errors)
