### ISSUE TITLE
Make site base url configurable (probably via an env var)

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1283]
Ref: https://github.com/18F/calc/pull/1263

From [this comment](https://github.com/18F/calc/pull/1263#discussion_r97120212):
> So, I can't actually dynamically generate a link back to the admin page for this email because it is sent in a scheduled task, so I have no request to use for build_absolute_uri. I could hardcode the production URL (or pass in as a default parameter), but then it seems like I should do that for all the other email methods. I guess I'm actually ok with that now that I think about it, because we don't need anything else from request.

We tried using the Django Sites Framework in #1270, but determined it was not a very good approach (mostly because that framework is confusing, poorly documented, and strangely implemented).

**Comment by toolness** [comment]
Blerg I guess we could still go with the sites framework if we want. That does seem to be the recommended way to define what a site's domain is outside of a request context. The main thing to avoid is just trying to create a data migration that changes the default from being example.com.

**Comment by toolness** [comment]
Oh, I guess another potential reason for using the sites framework is that I suspect third-party django apps will use it if needed.  So for instance, if we find some kind of third-party django app that, uh, sends emails outside of a `request` context, it might be built to support the `sites` framework rather than taking a base URL as a string or something. I dunno.

**Comment by jseppi** [comment]
Or stop needing the domain outside of a request context and do away with the whole problem :)

**Comment by toolness** [comment]
Hmm do you mean removing the links back to the site from the emails?  I think that's really useful, though...

**Comment by jseppi** [comment]
The only impacted email would be the approval reminder message. The link is useful, for sure.

**Comment by toolness** [comment]
Hmm, so I'm working on #1407 and realizing that the HTML email designs in #1208 might require us to embed `<img>` tags in the HTML emails, which ought to point back to the server... I suppose that doesn't actually change things, since the approval reminder email is still the only one that never has access to a `request` object, but I figured it might be worth mentioning, for some reason.

I guess that despite the fact that the sites framework is really weird, I think the biggest factor in favor of it is what I mentioned a few comments up, about third-party Django packages integrating with it.

Do dev/staging instances wipe their databases every time they're re-deployed, or do they stick around?  If they stick around, I don't think it's that big a deal to go into the django admin and set their site domains, but if they get wiped on every deploy then we'd have to set the site URL as part of the deployment script, which would be annoying.

**Comment by jseppi** [comment]
Databases are not wiped on deploy

**Comment by jseppi** [comment]
Closed as part of #1407
