### ISSUE TITLE
Document custom Django commands

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1290]
We have a number of custom django management commands (`ultratest`, `send_example_emails`, etc.). We should document them all in a section in our README to make it easier for new people to find them, and for us to remember them :)

**Comment by toolness** [comment]
Hmm, while I do like the idea of documenting them in the README, I'm a bit more inclined to have them be documented as part of existing "guides" rather than e.g. making a section on `manage.py` commands (since the latter can be explored interactively via `manage.py --help`, and the two could get out of sync).

For instance, `ultratest` is already documented front-and-center in the **Testing** section of our readme, and while we're not yet documenting `send_example_emails`, I think it'd be nice to mention it in the **Reading email** section, which already exists (or perhaps putting that section under a more generic **Reading and sending email** section, where we can also mention `sendtestemail`).

I guess we could have *both* a reference section and mention the commands in our guides, much as Django's docs themselves do--my only concern there is that the docs don't get out-of-sync with reality!

**Comment by jseppi** [comment]
Yeah, that's a fair point about having the docs get out of sync. Maybe we could add a section that is basically just a list of the commands with a high-level description of each, and direct anyone who wants the full documentation to use `manage.py [comand_name] --help `.
