### ISSUE TITLE
Data Explorer table sort indicators always show on second line

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1305]
<img width="991" alt="screen shot 2017-01-31 at 4 04 41 pm" src="https://cloud.githubusercontent.com/assets/697848/22486429/14c0f004-e7cf-11e6-8d33-8ea31f985ca8.png">

**Comment by hbillings** [comment]
I just pulled the latest changes from develop and I have this:
<img width="986" alt="screen shot 2017-02-01 at 10 10 07 am" src="https://cloud.githubusercontent.com/assets/509309/22517533/a94109c0-e866-11e6-993a-b4d0472f0db7.png">

Is this on prod or local? I think it should have been fixed in the `error_tables` branch.

**Comment by jseppi** [comment]
I'm seeing the indicators on a second line in locally on the `develop` branch and on all deployments (https://calc-dev.app.cloud.gov/, https://calc.gsa.gov, etc).

**Comment by hbillings** [comment]
My bad, the fix is actually in #1285
