### ISSUE TITLE
Release process - GitHub Release heading is whacky

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1306]
I think we just need to add an extra newline to the top of the `tag-message-v#.#.#.txt` that is generated. Or maybe make the first line the date, as we have on `/updates/`. 

Screenshot:
<img width="1011" alt="screen shot 2017-01-31 at 11 41 11 pm" src="https://cloud.githubusercontent.com/assets/697848/22496372/d0c72ffe-e80e-11e6-9eab-8e04c5019ed1.png">

from: https://github.com/18F/calc/releases/tag/v2.1.0

**Comment by toolness** [comment]
Yeah, bleh.

Part of what's going on here is that the tag message, as with commit messages, interprets `#` as a comment... yet because we're pasting the markdown into the tag message, it means that our *headings* are being ignored, since markdown headings begin with `#`'s too.  That's why our "Added", "Changed" etc headings aren't showing up there.

I am hoping that we can just have the first line be a blank newline, and not have any text be used as a heading.

**Comment by jseppi** [comment]
I'm fine with no heading

**Comment by toolness** [comment]
Wait, what page did you take that screenshot on?  I had seen that before too, but now when I visit https://github.com/18F/calc/tags, I see the following:

<img width="1002" alt="screen shot 2017-02-03 at 11 16 46 am" src="https://cloud.githubusercontent.com/assets/124687/22598688/509006e4-ea02-11e6-81a5-ab47d9a36530.png">

In other words, no more whackyness.  So it's possible this was actually a bug on GitHub's side that they've basically fixed through a sort-of redesign of that page, maybe?

**Comment by jseppi** [comment]
It still shows up weird. Link at the bottom of the initial issue comment :)

**Comment by toolness** [comment]
Ohh got it. 

Ok so I'm tinkering with this in a private repo and it's hard to figure out what exactly is making the thing wonky. Just adding a blank line to the top of the tag message doesn't seem to change anything--it's like GitHub is stripping all empty whitespace before the first non-commented out character, and then somehow deciding that first line should be in a massive font.

**Comment by jseppi** [comment]
barf :\ So maybe just add a timestamp at the top of that commit message text file?

**Comment by toolness** [comment]
Ooo!  No i got something!

How's this... here's what the `tag-message.txt` would contain:

<details>
  <summary><code>tag-message.txt</code> example</summary>
<pre>
Release v0.0.7

/// Added

- The new data capture functionality has been added, allowing COs
  to log in (via cloud.gov) and submit their approved Schedule 70
  price lists. Data administrators can then review these price lists and
  add their data into CALC.

- Additionally, data administrators can directly upload Region 10
  bulk data. The uploaded data will then replace all existing Region 10
  data in CALC.

/// Changed

- In October 2015, the schedules represented in CALC were consolidated
  into the [Professional Services Schedule][pss] to give federal agency
  acquisition professionals the ability to obtain total contract solutions
  for their professional services requirements using one contract vehicle.

  Consequently, the "Schedule" filter in the data explorer has
  been renamed to the "SIN / Schedule" filter, and allows rates to be
  filtered by SIN number.

- Searching for multiple words in the data explorer's search field
  now produces expected autocompletion results.

- The data explorer is now much more keyboard-accessible and
  screenreader-friendly.

- The "proposed price" field in the data explorer automatically
  updates the histogram on a per-keypress basis; there is no longer
  any need to click the "Go" button.

- Sharing CALC links with the "Education" field filled out now works
  properly.

- The CALC banner has been redesigned to be less confusing and easier
  to read.

- Google Analytics for CALC now properly track new searches in the
  data explorer as page views. We also track clicks on links in the
  "Contract #" column of the data explorer results table.

[pss]: https://www.gsa.gov/portal/content/246403
</pre>
</details>

Which looks like this:

<img width="1007" alt="screen shot 2017-02-03 at 12 14 39 pm" src="https://cloud.githubusercontent.com/assets/124687/22600847/61cabfa0-ea0a-11e6-898d-509ba8bc5844.png">

So that basically means adding "Release vX.Y.Z" to the top and substituting all `#`'s in headings with `/`.

**Comment by jseppi** [comment]
nice, that looks great!
