### ISSUE TITLE
Content Spoofing via Text Injection

### ISSUE THREAD

**Issue by hollyallen** [18F/calc#1372]
From the penetration testing conducted as part of the ATO process, reported here: https://docs.google.com/document/d/1C6ZddThph2ipC2_Obni5OulVmED-joGfBDJMPCJHniM/edit#heading=h.2jxsxqh 

Content spoofing is a type of an attack that allows malicious user to send faked or modified content to the application’s user as if it was legitimate.  

During testing it was discovered that application does not properly handle user input. Malicious user can supply content to web application via text manipulation in URL parameters. This can be used to present false information to the user and for website defacement. 

Affected Devices / URLs
https://calc-staging.app.cloud.gov/?q=ANYTHINGandANYLENGTH

Solution
User input has to be properly sanitized. If application has to accept only certain content, whitelisting can be used. 

Risk Factor
This attack can lead to data spoofing and information misrepresentation. This can severely impact user’s trust. Since it is a low risk system and malicious user can only manipulate textual data, this finding classified as moderate. 

Other References
https://www.owasp.org/index.php/Content_Spoofing
https://cwe.mitre.org/data/definitions/345.html

**Comment by hollyallen** [comment]
Related to #1354 but I created this issue to capture the full finding. This doesn't need to be fixed before ATO, but should be prioritized and fixed before other things.

**Comment by jseppi** [comment]
Hrm, the labor category search is a free-text field and I'm not sure we could or would want to do much sanitizing/whitelisting on what folks can search for. I somewhat disagree that this is "content spoofing" since the text is presented as what the user searched for, not any official content, but maybe we could make that more clear.

Would perhaps putting the search term in quotation marks make this more apparent?

As noted in #1354, the length of the query can certainly be an issue, especially if someone floods the page with a bunch of junk, though I think the issue there is just that it makes the page hard to read.

cc @toolness @hbillings

**Comment by jseppi** [comment]
Also, the query is "sanitized" in that HTML elements won't be injected since React DOM escapes values before rendering (see https://facebook.github.io/react/docs/introducing-jsx.html#jsx-prevents-injection-attacks).

**Comment by hollyallen** [comment]
The main finding is about presentation, and that a malicious actor can create arbitrary search urls and pass them around, and the page legitimizes that text as a valid search term. I'm seeking clarity on what a fix looks like.

**Comment by jseppi** [comment]
Thanks, @hollyallen!

Maybe we could simply remove the search query from the "Showing 24 of 24 results with <query>" part of the page since it is already shown in the search box.

**Comment by toolness** [comment]
Hmm, I'm curious how something like [https://www.google.com/search?q=blargy+blarg+blarg+pompzomdpmpzomv](https://www.google.com/search?q=blargy+blarg+blarg+pompzomdpmpzomv) is *not* content spoofing?  Or do we just need to make it extra clear that the search term is something the user provided, rather than something that may represent authentic content on the site?

For instance, Google says the following:

> Your search - **blargy blarg blarg pompzomdpmpzomv** - did not match any documents.

This is a bit different from, say:

> **blargy blarg blarg pompzomdpmpzomv** did not match any documents.

As the first version emphasizes that the search term is something provided by the user.

**Comment by hollyallen** [comment]
Agreed @toolness . I'm not sure why they characterized it this way. The pen testers are saying that #1354 will fully resolve this. I want to add that your suggestions are good, and the idea is to make it very clear what is user provided vs app provided. 

We ran into this on another project which (previous to fixing the finding with whitelisting) used URL content as part of the h1 content on the page. That really legitimized spoofed content!
