### ISSUE TITLE
Consider increasing max experience in CALC to "infinity" (or user-provided value)

### ISSUE THREAD

**Issue by toolness** [18F/calc#1405]
One of Kelly's asks for the price list analysis functionality in #997 is to have the upper bound of experience be unbounded.  However, because the design philosophy behind the analysis is to link the short analysis blurb to an actual CALC query for deeper investigation, this is impossible, as the maximum years of experience in the UI is capped at 45.

Given that there's apparently a use case in price analysis to search beyond 45 years of experience (!!), it might be nice to allow this in the UI too.  One way to do this while keeping the slider intact might be to add one final option after 45: ∞.

**Comment by hbillings** [comment]
So I was looking at that slider again and realizing I can't tell precisely what it does! I was assuming, I guess, that it sets the range of acceptable _minimum_ values, not the lower and upper bounds for experience. Damn, we need to label this thing better.

I'm not convinced the slider is all that helpful to users, tbh. I think something like this, set for the five-year intervals we've seen folks search for, might be a better pattern (from Amazon):
<img width="206" alt="screen shot 2017-02-21 at 9 57 18 am" src="https://cloud.githubusercontent.com/assets/509309/23175457/a80ba7c0-f81c-11e6-8707-ec14b4e130b3.png">

If the box set to 45 by default does represent minimums: Do we have data in CALC that have a min experience greater than 45? I kind of think that it should represent the largest number we have a row for. It's a nice way to let people know what the possible range of results will include, a la something like this (from Banana Republic):
<img width="318" alt="screen shot 2017-02-21 at 10 02 40 am" src="https://cloud.githubusercontent.com/assets/509309/23175543/f978ad74-f81c-11e6-9bb7-ce502255de50.png">

Either way, I'd vote for "any" over "infinity" because it isn't actually possible to have infinity experience. Unless you're Buzz Lightyear. In which case, I might be Jessie the Yodeling Cowgirl.

**Comment by toolness** [comment]
LOL we should totally just have "Buzz Lightyear" instead of ∞ or "any" 😁 

Good suggestions!  Let's bust it up.

**Comment by ericronne** [comment]
I think sliders are engaging and serve to nicely visualize a span like experience. I'd be curious to see if users are grabbing them. cc @tram 

Looks like 42 is the max experience currently in calc. This returns 2 results:
![image](https://user-images.githubusercontent.com/9259185/41795626-087d5d5c-7629-11e8-8a63-60e0b8b4384d.png)

https://calc.gsa.gov/?min_experience=42

If the number on this widget changes dynamically as the user enters a labor category into the search field, that could serve as a nice preview of the results that the user will get when they execute the search.

@KellyBailey would @hbillings's suggestion to limit the years to what's in the data accommodate the use cases you can think of?
