### ISSUE TITLE
Histogram label overlays on multiple filters

### ISSUE THREAD

**Issue by maya** [18F/calc#163]
Whenever a filter is added, an additional label gets created and overlays on top of each other. This gives the label a bold, pixelated appearance and makes it hard to read.

Here is what it looks like with all filters selected:
![screen shot 2015-05-19 at 11 35 19 am](https://cloud.githubusercontent.com/assets/5249443/7710890/cda22ad8-fe1b-11e4-99a9-6756016279fa.png)

Normal:
![screen shot 2015-05-19 at 10 42 26 am](https://cloud.githubusercontent.com/assets/5249443/7710877/aecadf92-fe1b-11e4-872d-8c7de63719e3.png)

Multiple labels:
![screen shot 2015-05-19 at 11 36 22 am](https://cloud.githubusercontent.com/assets/5249443/7710880/b983b0f8-fe1b-11e4-9b74-7003f9dcf172.png)

**Comment by openbrian** [comment]
Hey there.  2 weeks ago i participated in the GSA Hackathon.  We used NVD3 for the chart on our project.  I think it works quite well, because it handles chart building for you, much like HighCharts.  It will take care of your issue here.

A few days ago, i forked calc to see what nvd3 would look like.  It's nice, but it doesn't label the buckets "between" the buckets as the 18F project does.  The buckets in my project label the bars based on the average Price.  Anyway check it out.  https://github.com/openbrian/calc

As a side note, i was also able to label the buckets with the ranges  $min - $max, but that looked ugly, even when they were rotated 45°.  With some JS hacking, i  could use just the min of the range and offset the x-position of the label.

**Comment by openbrian** [comment]
An up to date demo of NVD3 charts is here https://nvd3-community.github.io/nvd3/examples/site.html

**Comment by maya** [comment]
Hey @openbrian, just wanted to say thanks so much for your work forking this! It's definitely informed a few ideas we've had moving forward with the histogram design, so thanks for that!

**Comment by openbrian** [comment]
You're welcome.  I hope NVD3 works out despite it's IE9 misgivings.  I gave @brethauer a few ideas about that over email.
