### ISSUE TITLE
Pin to minor version of Python runtime

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1630]
As @jmcarp [pointed out](https://github.com/18F/calc/commit/c42203a900e4ccf5358873b8d475f4c810c818a9#r28162037), we can pin to `python-3.6.x` in `runtime.txt` instead of to a specific patch version.

This seems like a great idea to me!

**Comment by toolness** [comment]
I like that idea for `runtime.txt` because cloud.gov takes care of ensuring we're on the latest patch release whenever we re-push, but should we do it for other stuff, e.g. the docker config?

To be honest I noticed there are some pretty significant changes between the first version of 3.6 and 3.6.2, so I wouldn't mind us making it explicit in Docker-related stuff, lest we use new features introduced in a patch release and then someone's dev environment breaks because they're on the older version of Python but there's no way for docker to know the minor version changed.
