### ISSUE TITLE
CALC's CSS isn't responsive. Should it be? Research, discuss …

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1644]
How might a CALC user — or merely the CALCurious — benefit from a mobile-friendly experience?

Current site ...
![image uploaded from ios](https://user-images.githubusercontent.com/9259185/37716346-514fe85a-2cec-11e8-9006-cdca4f0eb1fc.jpg)
![image uploaded from ios 1](https://user-images.githubusercontent.com/9259185/37716353-558a7534-2cec-11e8-880c-15dc079371da.jpg)

**Comment by jseppi** [comment]
I think it would be great if the Data Explorer was responsive. Maybe not for "real use" but because when CALC is marketed/tweeted/talked about, a lot of people are going to end up bringing it up on their mobile devices, and presenting a polished look would be good.

The Data Upload doesn't seem as important to invest time in making very responsive.

**Comment by ericronne** [comment]
Plus 1,000!

Conference attendee hears CALC mentioned in a talk, pulls out her phone to see what the hubbub is all about ...

**Comment by toolness** [comment]
I changed the issue name to say "CALC's CSS isn't responsive"... I know that may not be technically correct, but when I see "CALC isn't responsive" I keep thinking "OMG CALC IS DOWN" when in fact it is not.

**Comment by hbillings** [comment]
Agreed; the data explorer should definitely be responsive. This is gonna be fun with all the D3 on that page 😬
