### ISSUE TITLE
Replace current WDS implementation

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1657]
The way we're using the WDS right now is not updateable. Basically, I copied the bits of the system we needed at the time and pasted them into correspondingly named files in `frontend/source/sass/uswds/`. My thinking was that we're actually using very little of the WDS and I didn't want to glob a huge bunch of unnecessary code onto the site. (Also, as @toolness reminds me, building on to the existing bespoke code was tricky at the time.) But it's also impossible to update, and it's a pain to extend or to take advantage of parts of the WDS that aren't already here. Also, none of the current styles have the `usa` prefix, which brings up issues mentioned in #1646.

I'm thinking we should rip out the current implementation and replace it with an `npm install` version of the system. I still don't like the bloat, but I guess it seems better to have the bloat than a fragile system. What say you all?

**Comment by toolness** [comment]
That sounds good to me, if you think it's doable!  It definitely makes using django-uswds-forms (and any other potential tools that might rely on the standards) easier.

That said, not supporting alternative prefixes to `usa-` could also be considered a bug in django-uswds-forms, especially since USWDS makes it so easy to change that prefix in its SASS, so I've filed an issue for that at https://github.com/18F/django-uswds-forms/issues/25.  But that still leaves the problem of e.g. django-uswds-forms using some class that we haven't manually decided to include in our thing.

I guess though, this also gets back to how USWDS itself is structured--ideally it'd be sort of, um, Foundation-like, I think, in that we'd be able to have our own SASS files that individually import in each USWDS feature we want to use.  And django-uswds-forms' documentation would include details on which of those SASS modules (or mixins, or whatever they're called in SASS-land) are needed for certain features to work properly.  But USWDS isn't currently structured that way, alas, so we probably should just bring in all of it...

**Comment by hbillings** [comment]
Oh, it's definitely doable. There will be a lot of swear words, but it's doable. 

The other option we have instead of using `npm` is downloading the SASS files, adding a version number to them, and then including the ones we want in our main SASS file. It's still harder to update than it would be if we used `npm`, but it's at least doable. And we'd get some of the ability to incorporate only the pieces of USWDS that we want. It's a bit crude and I wonder how well it would fare in the future with a different team, though.
