### ISSUE TITLE
Fix broken GSAAdvantage links

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1668]
It looks like GSAAdvantage has changed their URL schema, and now our links to contracts are broken. I spent a minute poking around, but I don't know how to even go about finding contracts on GSAAdvantage.

**Comment by hbillings** [comment]
Interesting: Only links that start with `GS` work. For instance, the middle link in this screenshot works, but the one above and below 404.
<img width="920" alt="screen shot 2018-03-26 at 11 40 29 am" src="https://user-images.githubusercontent.com/509309/37922692-847112ac-30ea-11e8-9448-e820d4c426d1.png">

**Comment by jseppi** [comment]
Alternatively, or maybe as an interim fix, we could change our code to only link “GS” contract numbers.

**Comment by toolness** [comment]
Hmm, I'm super confused as to where these contracts that don't start with "GS" are even coming from--are we sure they existed a year ago?  I think the vast majority of the data in CALC is coming from Kelly's R10 export, and it--well, at least the export from October 2017--seems to consist entirely of contracts that start with "GS".  So either those non-GS contracts are in a newer version of the R10 export, or ... honestly I can't even imagine they're coming from IT 70 uploads because the schedule isn't always IT 70!

Another weird thing is that searching for those exact contract numbers in [GSA Advantage's advanced search](https://www.gsaadvantage.gov/advantage/s/advncdSearchSrvsEnter.do) (which lets you specifically search by contract number) isn't yielding any results.  Searching for the contracts that start with "GS" works fine, but... I'm starting to wonder if these non-GS contract numbers might somehow be the result of bad parsing or something else weird.  I am very confused.

**Comment by jseppi** [comment]
I think these may have been added via price list uploads recently. There have been a number of folks uploading and approving price lists the past month or so.

**Comment by toolness** [comment]
But I thought that only IT 70 can upload price lists? Shouldn't the "Schedule" column for the non-GS contracts be "IT Schedule 70"?  Yet just in the screenshot Heather posted above, the Schedule of the non-GS contracts is Consolidated and Logistics...

**Comment by jseppi** [comment]
That is very strange...great sleuthing! We should definitely ask Kelly!

I just took a peak at some of the uploaded and approved price lists that are in production CALC, and there are a few in there that have non `GS-` contract numbers as well. Here's a quick screenshot of some of them:

<img width="321" alt="screen shot 2018-03-30 at 8 41 04 am" src="https://user-images.githubusercontent.com/697848/38139684-27f28f38-33f6-11e8-9b1b-cd4b177764b6.png">

**Comment by toolness** [comment]
Ah cool!  So as (I think?) Kelly said on the call earlier today, those super-long but non-GS contract numbers _are_ valid... I double-checked on GSA eLibrary and they do show up in searches. For instance, here's the one for [47QTCA17D0008](https://www.gsaelibrary.gsa.gov/ElibMain/contractorInfo.do?contractNumber=47QTCA17D0008&contractorName=PSI+INTERNATIONAL%2C+INC.&executeQuery=YES).

However, the GSA Advantage link for that one will fail, but not because it's unrecognizable to GSA Advantage: I think it's just such a new contract that GSA Advantage doesn't have it yet.  In fact, there's a column for "Contractor T&Cs/Pricelist" on eLibrary that normally links to the GSA Advantage pricelist for the contract, and it's populated for [GS-10F-0281P](https://www.gsaelibrary.gsa.gov/ElibMain/contractorInfo.do?contractNumber=GS-10F-0281P&contractorName=LOGISTICS+SOLUTIONS+GROUP%2C+INC.&executeQuery=YES), but not for 47QTCA17D0008.

**Comment by toolness** [comment]
FWIW, my brand-new [GSA eLibrary scraper](https://github.com/18F/calc-analysis/tree/master/elibrary-scraper) provides information whether GSA eLibrary thinks that GSA Advantage has a pricelist available.  So we could potentially query that to determine whether or not to actually hyperlink the contract number for really new contracts.

**Comment by toolness** [comment]
Hmm, I'm now wondering if it's possible for the same contract to have multiple contract numbers, or for the contract number to change at some point.  For example, CALC claims there's a contract `BF045HA` (a bizarro number which translates to `GS-00F-045HA`) with a "SLICKFORCE, INC".  Searching GSA eLibrary reveals that no contract with that number exists, _but_ it does claim that there is a contract `47QRAA18D000W` with the same company.  I looked up the contract's [pricelist PDF](https://www.gsaadvantage.gov/ref_text/47QRAA18D000W/0SEF5F.3KQC81_47QRAA18D000W_SLICKFORCECATALOG2.PDF) and it seems to mention some (possibly all) of the labor categories CALC knows about.  It's also a relatively new contract whose period started Oct 31, 2017.  So I'm wondering if maybe the contract was _originally_ given the number `GS-00F-045HA` but that it perhaps later changed to `47QRAA18D000W`, perhaps when this new numbering scheme took effect?

**Comment by toolness** [comment]
Ok, I learned more about this!

* The contract number is apparently technically referred to as a **Procurement Instrument Identification (PIID)**.  Aside from being much more useful for web searches, this acronym also explains part of why the contract number field in our `Contract` model is called `idv_piid`.  Still not sure what the `idv` part means, but at least we know what the `piid` means now.

* Federal News Radio's article [Agencies get 2017 deadline to move to new procurement ID standard](https://federalnewsradio.com/management/2014/10/agencies-get-2017-deadline-to-move-to-new-procurement-id-standard/) has a great explanation of what the new PIID format consists of:

    > The PIID will require agencies to use a combination of 13 to 17 alpha and/or numeric characters sequenced to convey certain information. The first six numbers should be used for the Activity Address Codes (AACs), which are a unique identifier for contracting offices and other offices. The next two numbers are for the fiscal year of award or action, and the ninth place should be an agencywide standard for the type of contract or vehicle, such as blanket purchase agreement or task order, the agency is using.

    So, for instance, this means that the `18` in `47QRAA18D000W` refers to 2018.

As far as I can tell, though, there still doesn't seem to be a well-defined mapping for how to go from the old-style PIIDs to the new-style ones.  So we might just have to resort to encouraging data administrators to update this information, though we could potentially suggest new PIIDs via GSA eLibrary scraping.

**Comment by ericronne** [comment]
IDV seems to mean "Indefinite Delivery Vehicle" …
https://www.fpds.gov/help_V1_1/Indefinite_Delivery_Contract.htm

**Comment by KellyBailey** [comment]
I will have a new pricing export today which I think will solve that issue. Apparently, someone had the bright idea of using the truncated contract number in our internal database as a primary key instead of the longer contract number. I'll let the team know if the new upload fixes the issue.

**Comment by toolness** [comment]
Wooo this is fixed in production now, as of [2.8.6](https://github.com/18F/calc/releases/tag/v2.8.6) and Kelly's bulk upload just now.
