### ISSUE TITLE
Production site API pages are not loading CSS/JS/image static assets

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1694]
When visiting https://api.data.gov/gsa/calc/rates/, we should see a nice Django Rest Framework page that looks something like:

<img width="575" alt="screen shot 2018-04-03 at 9 11 37 am" src="https://user-images.githubusercontent.com/697848/38254530-24b05e82-371f-11e8-93cf-3cdea3f4eb78.png">

However, we get an unstyled page that looks like:

<img width="641" alt="screen shot 2018-04-03 at 9 09 31 am" src="https://user-images.githubusercontent.com/697848/38254551-31f9a99a-371f-11e8-9b41-f76bacfefc25.png">

Here's what the console shows:

<img width="630" alt="screen shot 2018-04-03 at 9 13 43 am" src="https://user-images.githubusercontent.com/697848/38254592-49eb117e-371f-11e8-9cb5-57823cd3893b.png">

**Comment by toolness** [comment]
Hmm, I suspect making this work would require us to set [`STATIC_URL`](https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-STATIC_URL) to an absolute URL like `https://calc.gsa.gov/static/` or `https://calc-prod.app.cloud.gov/static/` on production, so that static assets aren't referred to with a relative path.

That said, even once we get the static assets displaying nicely, we might face other problems. For instance, there's a button labeled **OPTIONS** on that page with the following HTML:

```html

<form class="button-form" action="/api/rates/" data-method="OPTIONS">
  <button class="btn btn-primary js-tooltip" title="Make an OPTIONS request on the Get Rates resource">OPTIONS</button>
</form>
```

Given that the action is `/api/rates/`, which makes sense for calc.gsa.gov but not api.data.gov (where CALC's API is mounted at `/gsa/calc/rates/`), that button might not work.

Er, for that matter, even the unstyled screenshot above is displaying incorrect information: it says `GET /api/rates/` at the top, despite the URL in the address bar pointing at `/gsa/calc/rates/`.

**Comment by toolness** [comment]
Actually, I wonder if [Django's `sites` framework](https://docs.djangoproject.com/en/2.0/ref/contrib/sites/) might come in useful here?  It's made to allow a single instance of a Django project to power multiple websites, so technically we might consider `api.data.gov` and `calc.gsa.gov` to be two separate sites that are being served, each with different URLconfs.

**Comment by toolness** [comment]
Well, another approach might also be to simply rename `/api/` to `/gsa/calc/` on the local Django app... this would (mostly) bring the API routes on CALC in-line with the routes on api.data.gov, with the exception of the static assets.
