### ISSUE TITLE
Compile styleguide css as sass

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1878]
The styleguide has minimal styling itself, so it was originally fine to have it as plain CSS. However, with the inclusion of the color palette, it became clear that not having access to `_variables.scss` was particularly painful and would create doc rot over time. If we compile the guide CSS from Sass, it'll be easier to keep up to date.

**Comment by toolness** [comment]
Uh, wait... since the styleguide is already a minimal amount of CSS, want to just move it into our monolithic SASS bundle?  The only downside will be that it will get included as part of the compiled CSS that every page loads, but it's an easy fix that doesn't require adding any extra logic to the gulpfile. If it ever gets really big we can always move it into its own separately-compiled SASS/CSS file...

**Comment by hbillings** [comment]
I'm fine with that! I can do that as part of #1858.
