### ISSUE TITLE
Use relative paths or a SASS variable to locate the static root

### ISSUE THREAD

**Issue by toolness** [18F/calc#1895]
I noticed that some of our SASS files hard-code the absolute path `/static/` as the static root, e.g.:

```css
.thing {
  background: url(/static/admin/img/icon-addlink.svg) 0 4px no-repeat;
}
```

I think we should follow Django best practices here and decouple the absolute location of our static files from our code as much as possible, so that it's easy to e.g. relocate to a CDN if needed (although I suspect this won't ever happen, I think it's still a good best-practice to follow).

Since this is SASS, we could do that either via a relative URL or a SASS variable (e.g. in `_variables.scss`).  If we use a SASS variable, we should probably put a comment above its definition that mentions that it should stay in sync with [`settings.STATIC_URL`](https://docs.djangoproject.com/en/2.0/ref/settings/#static-url).

**Comment by tbaxter-18f** [comment]
I agree with Atul that hard-coding the absolute path is probably problematic long term and is definitely a pattern to avoid, but I think a simpler answer would be to simply leverage the predictable relative paths. 

Because files going into /static/ are put there systematically, we know the system, and can know exactly the relative paths /css/ has to siblings.
