### ISSUE TITLE
Consider adding an explanation to the data quality report

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1906]
It would be nice to show users a brief explanation of why they're seeing the stats they're seeing on the data quality report, because things seems like they might ought to be changeable (for instance, the education/rate paragraph seems like I ought to be able to choose education level and hourly rate to see what's in there, but that's way beyond the scope.)

**Comment by toolness** [comment]
Hmm, I don't think any of the fields should be changeable--if they are, that indicates that we should find a better metric, IMO. Otherwise there's no way for admins to get a really quick idea of how "healthy" the data is.

In the case of the education/rate paragraph, that's really just a quick-and-dirty proxy for outliers--ideally we'd be using an anomaly detection system for that like the one I put in [calc-analysis](https://github.com/18F/calc-analysis/blob/master/contract-analysis/anomaly-detection.ipynb). I'd much rather put effort into building that out, than making the reporting super configurable (which really requires people to manually find outliers than an anomaly detection system would find automatically).

**Comment by hbillings** [comment]
Oh, totally, I didn't mean it _should_ be changeable, just that the way it's worded makes it _seem_ like it should be (at least to me), so I'm confused when I can't change it. I think it just needs some explanation about why we're showing these particular stats, because without context, I don't know why those numbers matter.

**Comment by toolness** [comment]
Ahh, got it!  That makes sense.

**Comment by hbillings** [comment]
We chatted about the fact that it would probably be nice to add a quick li'l sentence at the top to indicate what data this report is looking at (stuff that's currently live in CALC, as opposed to retired price lists).

**Comment by toolness** [comment]
Ok I think this is fixed by #1938 so I'm gonna close it, but feel free to re-open if you disagree!
