### ISSUE TITLE
As a contracting officer, I would like the flexibility to add new SIN or schedule numbers or name.

### ISSUE THREAD

**Issue by KellyBailey** [18F/calc#1924]
As a contracting officer, I would like the flexibility to upload a price list and have flexibility to add new SIN or schedule numbers.

**Comment by toolness** [comment]
I have the same confusion about what exactly a "SIN number" means in this context that I described in https://github.com/18F/calc/issues/1928#issuecomment-393876846.

If we're going with definition 1--that SIN number is merely an alias for Schedule--then we have some additional questions (I'm ignoring definition 2 because I have no idea how to proceed with that case).

Currently we have two kinds of ways to upload data: via individual price list, and via R10 bulk upload.

For **individual price lists**, the schedule for all the rows in an individual price list is set by looking at the `title` attribute of the schedule's `data_capture.schedules.base.BasePriceList` subclass.  Aside from being hard to change architecturally, it's also unclear what changing it would mean, because it's assumed that each schedule has totally different price lists that require different business logic to scrape.

For **R10 bulk upload** this question is a bit easier to answer, because R10 bulk uploads are assumed to have labor category rows for different schedules. We don't even validate the schedule name in any way, so it's actually entirely possible for a R10 bulk upload to contain new schedule names: they will even be listed in the "schedule" column of the Data Explorer, _but_ they won't be listed in the [SIN / Schedule](https://user-images.githubusercontent.com/124687/40842236-3625183a-657b-11e8-815a-65f766cedb58.png) dropdown because that's currently hard-coded.  If this is the context we're talking about, then resolving this issue is doable--we'd essentially need to make the SIN / Schedule filter dynamically generated, either by looking at all unique values of the `Contract.schedule` field, or providing a new `Schedule` class that admins can manage, or something similar.

**Comment by ericronne** [comment]
Closed by #2018
