### ISSUE TITLE
As an acquisitions professional, I would like to be able to filter for new SIN numbers for new data uploads.

### ISSUE THREAD

**Issue by KellyBailey** [18F/calc#1928]

**Comment by toolness** [comment]
There's a few things that confuse me about the title of this issue.

## What is a SIN number?

I'm confused as to what "SIN number" means in this case, as well as some other cases. It stems from the fact that we actually have two different concepts of "SIN number" in CALC:

1. The schedule name, as shown in the filter drop-down:

    > ![schedule](https://user-images.githubusercontent.com/124687/40842236-3625183a-657b-11e8-815a-65f766cedb58.png)

    This is essentially a one-to-one mapping between the "Schedule" column of our data table and a SIN number.  It's easy to filter by this kind of SIN because our "Schedule" column is well-formatted.

2. The `sin` field in our `Contract` model. This is _very_ inconsistently formatted, as documented in #1033.

If by "SIN numbers" this issue means definition 1, then this should be easier to implement. On the other hand, I have no idea how we'll implement it if the issue is referring to definition 2.

## What does "filter for new SIN numbers for new data uploads" mean?

Even once we've ascertained what a SIN number means in this context, I'm not sure what it means to filter for new SIN numbers for new data uploads.  Are we talking about an e-mail notification that tells users when new kinds of SIN numbers are available in CALC?  Or are we talking about a new filter criteria in the Data Explorer?  Or something else?
