### ISSUE TITLE
As a user, I would like to be able to search by Company Name or contract number.

### ISSUE THREAD

**Issue by KellyBailey** [18F/calc#1930]

**Comment by toolness** [comment]
At a data and technical level, this is straightforward because we've already got data on company names and contract numbers.  The hard part here is just figuring out how to expose this functionality in the UI without making it feel overwhelming or confusing.

One way might be to adopt something similar to the way Slack and other services allow different kinds of search criteria to be specified in the search box. For example, we could make it so that a search for `engineer vendor:Blarg` would search for engineers from the "Blarg" company, or `technician contract:GS-00F-184GA` could search for technicians in the GS-00F-184GA contract.

There's a number of advantages to this approach:

* The search UI scales linearly; we can easily add more search criteria without worrying about cluttering the UI, and it's easy for users to learn new search criteria without having to learn whole new UX patterns.
* The pattern already exists in other best-of-class products like Slack and Google, so some users will already be familiar with it.
* Search is just a string, which makes it easy for users to copy/paste if needed. (It also makes the functionality super easy to unit test.)
* It's relatively easy to implement. A first pass could just implement the basic functionality without necessarily offering any kind of autocomplete UI, while a separate iteration could make the functionality more discoverable by supporting autocomplete similar to that of existing best-in-class products.
