### ISSUE TITLE
"Contains Words" search not working

### ISSUE THREAD

**Issue by KellyBailey** [18F/calc#2052]
![image](https://user-images.githubusercontent.com/12072003/42775414-23a3b4dc-88e9-11e8-8751-e90400485fdb.png)

**Comment by tbaxter-18f** [comment]
Possibly related to https://github.com/18F/calc/issues/209

**Comment by tbaxter-18f** [comment]
OK, this is interesting. 

We know that there are results for "copy editor" in the database. If you search for "editor" you can see them. 
We know there are also other results that have "copy" in them. "copy writer", for example. Search for "cop" and you'll see those, too. If I search the DB directly, with `qs = Contract.objects.filter(labor_category__icontains="copy")` I see 111 results.
But if as soon as you add "y" to "cop" in the search, results drop to 0.

My working theory, which admittedly is a stretch, is that because `copy` is a SQL command, we're either stripping it out or mightily confusing the DB with it. Investigation continues.

**Comment by tbaxter-18f** [comment]
Should resolve #1058 too
