### ISSUE TITLE
Design the price list analysis experience

### ISSUE THREAD

**Issue by ericronne** [18F/calc#2075]
We already have a PR (#997) for a new feature enabling users to analyze a price list, to estimate the relative reasonableness of the rates on that list. We still need to flesh out some design implications for it, though, including (but not limited to) …
- [x] Rename two site tabs (this will make space for the new tab) :
      - "Analyze prices"
      - "Admin"
- [x] Remove the SIN column from step 3
- [x] Update remaining table headers to match verbiage found in data uploader
- [ ] Add detail phrases a la proposed price feature concept (#2030)
- [x] Fix button styles (see uploader for style)
   - [x] "Cancel upload" on step 2
   - [x] Step 3 buttons
- [x] Use narrower card style for steps 1 and 2 (see uploader)
- [x] Apply new step indicator format (enhancement)

**Comment by ericronne** [comment]
cc @tram @tadhg-ohiggins

**Comment by hbillings** [comment]
I'd really love it if we could move checklists like this to the PR body instead of the issue -- these are less acceptance criteria and more implementation details, which is more relevant to the PR than it is to the issue, IMO. (Also makes it way easier to tell what's going on with the PR without having to ping-pong back and forth between the two.)

**Comment by ericronne** [comment]
That works when the one doing the work is the one who made the list. Will try to do that when i'm the PR-er.
