### ISSUE TITLE
Verify that 2058-exact-match-checkbox defaults to the correct type of query

### ISSUE THREAD

**Issue by ericronne** [18F/calc#2111]
Relevant PR: #2108

@tbaxter-18f comment which gives @hbillings pause: https://github.com/18F/calc/pull/2061/files/d36ff5841d615dcb9d276c5c9304971a1af84d70#diff-0e1c0a82e7b537e49d2658fb166ae1ceR117

**Comment by hbillings** [comment]
After digging into this, I can confirm that, yes, we're using the right default search query (`match_all`).

However, this query requires all words in the search term to be present in the labor categories it returns (it just doesn't care about order or additional words), so "loquacious engineer" will return 0 results because no labor category contains the first term. This is the correct behavior based on the code that currently exists.
