### ISSUE TITLE
In Production app, search engines should be able to index CALC

### ISSUE THREAD

**Issue by jseppi** [18F/calc#299]
In the CALC production instance, remove the robots.txt that is `Disallow`ing search engine indexing: https://calc.gsa.gov/robots.txt

**Comment by jseppi** [comment]
@toolness - you could take a look at this one also. I guess we'd need a way to tell if the app is in "production mode". In node I'd look at `NODE_ENV`, but not sure about the practice for python or django.

**Comment by toolness** [comment]
Hmm, this is an interesting distinction, because it seems like we *do* want the anti-indexing `robots.txt` to be on staging, while a pro-indexing `robots.txt` is on production?

For staging/prod parity it seems like both of them use "production-like" settings, which in Django-land generally means `DEBUG=False`.  I think even in node-land, you'd want a staging server set `NODE_ENV=production` right?

This makes me wonder if it'd make sense to just have a separate `SEO_INDEXING` boolean setting, which defaults to `False` but that we force on in calc.gsa.gov and nowhere else, not even staging?

**Comment by jseppi** [comment]
> Hmm, this is an interesting distinction, because it seems like we do want the anti-indexing robots.txt to > be on staging, while a pro-indexing robots.txt is on production?

yes, exactly

I've done, `NODE_ENV='staging'` for node stuff, though you're right it's not 100% parity.

I think a separate env value like you suggest would be a good approach.

**Comment by toolness** [comment]
Yeah, another funky thing I've noticed is that a number of third-party libraries (React is the most recent that comes to mind) specifically check `NODE_ENV == "production"` to determine whether or not to do certain optimizations, so I've been afraid of setting it to anything other than `production` unless I'm actually developing locally. :worried: 

Cool sounds good!
