### ISSUE TITLE
Integrate 18F's glossary panel into CALC

### ISSUE THREAD

**Issue by toolness** [18F/calc#313]
I was just watching [Emileigh Barnes' Enterprise Storytelling Sessions talk](https://www.youtube.com/watch?v=HCI5LnEnTCI&t=14m52s) and she mentioned the use of the [18F Glossary Panel](https://github.com/18F/glossary#readme) as a way to onboard new visitors to the complex terminology used, out of necessity, on the FEC website.

I just tried using the panel and I think it could potentially be a great fit for CALC, especially since the CALC 1 team said that some contract specialists found the site's required terminology unfamiliar.  It could potentially be used in addition to, or as an alternative to, #296.

For a quick demo of the panel, [click on the word "fossil fuel" on this page](https://useiti.doi.gov/how-it-works/production/).

@hbillings do you think this might work from a usability standpoint? If so, would you be interested in prototyping this kind of integration?

**Comment by jseppi** [comment]
This could be really good, but I'm concerned with whether or not it falls into the scope of our current work.  We should get clarification on how much we should be adding to/modifying existing CALC functionality I think.

**Comment by ericronne** [comment]
Just discovered this issue! I do think such a tool would be useful for many, since that our users have varying amounts of experience — and CALC uses some decidedly uncommon terms. Here's a prototype to help us suss out the pros and cons of one. Please use the comment tool to discuss....

### [Glossary prototype](https://gsa.invisionapp.com/share/7J9QMEY94#/211262638_Glossary_Teaser)

*Note: i've ghosted back some elements in order to highlight glossary-related interface bits.*

#### Default
![image](https://cloud.githubusercontent.com/assets/9259185/21195341/0557006e-c1f9-11e6-9c6c-1740d03f8c6d.png)

#### Sample definition, with related terms
![image](https://cloud.githubusercontent.com/assets/9259185/21195347/09b89afa-c1f9-11e6-958b-06d7a134f4d8.png)

@hbillings @tram

**Comment by tram** [comment]
This is great, @ericronne!

**Comment by ericronne** [comment]
@jeremyzilar
