### ISSUE TITLE
Compliance - Incomplete or No Cache-control and Pragma HTTP Header Set

### ISSUE THREAD

**Issue by jseppi** [18F/calc#359]
https://compliance-viewer.18f.gov/results/calc/current

**Comment by jseppi** [comment]
Here's the description of why we would want to specifically tell the browser not to cache https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Web_Content_Caching

I guess on all pages behind the auth we should do this? I don't have a good handle on the implications.

**Comment by jseppi** [comment]
There is a `@never_cache` decorator we could use on sensitive views: https://docs.djangoproject.com/en/1.8/topics/cache/#controlling-cache-using-other-headers

**Comment by toolness** [comment]
Hmm, I agree that `@never_cache` makes sense for sensitive views, but some of the URLs that compliance viewer is complaining about are ones that publicly-available static assets exist at, e.g. the link to [aight](https://github.com/shawnbot/aight) JS.  Are we supposed to also never cache those or is it OK to mark them as false positives?

**Comment by toolness** [comment]
I'm also wondering if it makes sense to change any of our [`@login_required`](https://docs.djangoproject.com/en/1.9/topics/auth/default/#django.contrib.auth.decorators.login_required) (or more stringent) views to just include `@never_cache` as well, so that all our views behind authentication are also never cached. The only exception I can think of are publicly-available views that might happen to *also* include sensitive information if the user happens to be logged-in... hmm. I suppose it might make sense to just make all dynamically-generated content `@never_cache`'d just to be safe, then?

**Comment by jseppi** [comment]
I am pretty confused by this alert in general. Maybe get some guidance from
#compliance?

Sent from my iPhone

On Jul 13, 2016, at 12:37 PM, Atul Varma <notifications@github.com> wrote:

I'm also wondering if it makes sense to change any of our @login_required
<https://docs.djangoproject.com/en/1.9/topics/auth/default/#django.contrib.auth.decorators.login_required>
(or more stringent) views to just include @never_cache as well, so that all
our views behind authentication are also never cached. The only exception I
can think of are publicly-available views that might happen to *also*
include sensitive information if the user happens to be logged-in... hmm. I
suppose it might make sense to just make all dynamically-generated content
@never_cache'd just to be safe, then?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/18F/calc/issues/359#issuecomment-232430092>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAql-JGc5pxGbtg4pJ-JEcgs0qgGJcYpks5qVSJHgaJpZM4JGE9g>
.

**Comment by toolness** [comment]
Oh, I think I am mis-interpreting what this warning means. I think it means that we want explicit `Cache-Control` headers set on every page, letting browsers know exactly if/how to cache stuff, so that they don't make the determination on their own and guess wrong.

**Comment by toolness** [comment]
Wait, no, I am confused again.

Here's an example of a URL that compliance viewer doesn't like: https://calc-dev.apps.cloud.gov/static/hourglass_site/js/vendor/aight.v2.min.9d1d301beb80.js

That URL *does* have a `Cache-Control: public, max-age=315360000` header.  So we're being very explicit about the resource being public and cacheable.  I don't think that ZAP should have a problem with this.

Well, wait... upon further reading of that OWASP wiki page, it looks like they might want us to set `Cache-Control: no-cache="Set-Cookie, Set-Cookie2"`, so that while the actual asset itself is cached, the session cookie isn't?

**Comment by toolness** [comment]
Oh hey, this is totally related to #1260 and some of the stuff we've been doing to make sure production CALC doesn't fail with CloudFront.

**Comment by toolness** [comment]
I'm curious if ZAP will be happy with us now that #1260 has landed, or if it will still complain.

**Comment by jseppi** [comment]
Still waiting on this PR https://github.com/18F/concourse-compliance-testing/pull/129 to fix the CALC URLs in the automated scanning

**Comment by jseppi** [comment]
Looks like it still wants the `Pragma` header :(

**Comment by jseppi** [comment]
As mentioned in #358, automated Compliance Viewer scans are now up and running against prod.

I'm not quite sure what the `Pragma` header is even for or how it is different from `Cache-Control: max-age=0`

Also, I noticed that while we do have `Cache-Control: max-age=0` on URLs that return valid responses, we do not have that same header on error responses. I couldn't find anything in [Django's cache documentation](https://docs.djangoproject.com/en/1.8/topics/cache/) about special considerations for error pages :\ Do we need to add a custom middleware for adding cache headers to error responses (like our `ComplianceMiddleware` middleware does for security headers)? cc @toolness

**Comment by toolness** [comment]
So based on the [MDN docs for `Pragma`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Pragma) it seems like it's mainly used for backwards-compatibility with proxies/browsers that only support HTTP 1.0.  Which seems unlikely...

Good question about the error responses... I'm not sure what the best answer is, but one thing I did notice in the CloudFront tutorials I saw is that there are completely separate best practices for returning error responses...  CF seems to encourage actually storing the HTML for error pages on S3, so that CF can just serve those, which I guess is supposed to be particularly useful in the case of 504's, which might happen if the CALC django app crashes and CloudFront can't contact it for some reason...

There are also some funky CloudFront guidelines for varying the caching of errors based on the type of error that's occurred, e.g. they recommend setting fairly low cache timeouts for 500s, so that you can fix it and users can see the site working again shortly thereafter, whereas 404s--at least at certain paths, perhaps--could have longer timeouts, since it's more unlikely that those need fixing.

I guess that rather than configuring that stuff manually in CF, though, it probably does make sense for us to add middleware that sets the appropriate headers in the app...

**Comment by jseppi** [comment]
This seems to not have been an issue for the ATO, so I'm closing. Can re-open or create new if it comes up again.
