### ISSUE TITLE
New JavaScript pipeline

### ISSUE THREAD

**Issue by jseppi** [18F/calc#389]
Meta-issue for discussing new JS pipeline/build/style/etc.

My preference would be to use ES6 with npm-installed modules, built nicely into browser-ready ES5 via Babel and Browserify (as gulp tasks). However, that might be overkill, and we could potentially just go with what we're already doing, which is ES5, vendor'd libraries, and simple concatenation (via gulp).

Thoughts, @toolness @hbillings?

**Comment by toolness** [comment]
Rad!

I like webpack for its [code splitting](http://webpack.github.io/docs/code-splitting.html) and for some reason it fits my brain a tiny bit better--though I honestly find both browserify and webpack to be kind of complicated and confusing, so I am OK with either.  For browserify I guess I'm curious if it has anything similar to code splitting/chunking, so that we can e.g. lazy-load some massive library if needed (that said, we don't actually have a use case for such a thing, so it's OK if that's not available).

I like ES6 as long as we've got good source map support.

Um, this might be going overboard, but are either of you interested in trying out [TypeScript](https://www.typescriptlang.org/)? Its transpiler supports ES6, so we could use it as a replacement for (rather than in addition to) an ES6 transpiler. I've been using it for most of my recent JS stuff, but I can learn to live without it. We could also use ES5 with TypeScript, if we're worried that ES6+TypeScript might be cognitive overload for folks who have never used either.

**Comment by jseppi** [comment]
I don't expect that we'll end up needing code splitting since this is still a more traditional server-side driven app. I don't feel too strongly about gulp vs webpack for this project, aside from gulp already being setup somewhat. I do strongly prefer webpack for React projects though.

Sourcemaps appear to be supported with `gulp-babel`: https://github.com/babel/gulp-babel#source-maps

I would personally be interested in learning TypeScript, but I would lean toward being against it for this project. since it'll be another thing to learn, and another thing for future developers to have to know. ES6 on the other hand will eventually/has already started to replace ES5, so I think it is reasonable to use.

**Comment by toolness** [comment]
Cool, sounds good to me! So it sounds like we're thinking:

* browserify for modularization/bundling
* babel/gulp-babel for ES6 + sourcemaps

How about unit tests? I think we discussed mocha and tap before--I've used mocha on both the server and browser and like it... I'm ok with tap as long as there are browser runners for it! QUnit is fine too for that matter--I don't know if it's supported server-side, but since we're not writing any JS that runs on a server, I guess that's not an issue.

**Comment by jseppi** [comment]
I basically have no experience with browser tests, so I will completely defer to you and @hbillings on that issue.

**Comment by toolness** [comment]
Oh ok. @hbillings do you have a preference on any of the stuff we've discussed so far?

**Comment by hbillings** [comment]
All of this sounds good to me. I'm not really familiar with browser tests either, so it probably makes sense to go with whatever @toolness knows that he can disseminate knowledge on, heh.

**Comment by toolness** [comment]
Cool! Um, honestly I'm fine with just sticking with QUnit. That way we don't have to convert the existing QUnit test suite or confuse newcomers by having two different browser-side test suites, and we've already got the QUnit tests running in phantomJS during travis CI too (#287) so everything is all set up.

@jseppi would you be interested in setting up the pipeline?

**Comment by jseppi** [comment]
Sure thing!
