### ISSUE TITLE
Date fields should each be 3 separate fields

### ISSUE THREAD

**Issue by toolness** [18F/calc#534]
As mentioned in #415, the [Date input](https://standards.usa.gov/form-controls/#date-input) section of the USWDS claims that three text fields are the easiest way for users to enter most dates:

> <img width="219" alt="screen shot 2016-08-08 at 3 32 32 pm" src="https://cloud.githubusercontent.com/assets/124687/17493223/5ee62794-5d7d-11e6-9319-997bd9204019.png">

Currently our date fields are just standard text input fields, and we've observed at least one user enter the incorrect format in testing sessions.

It seems like Django's [`MultiValueField`](https://docs.djangoproject.com/en/1.9/ref/forms/fields/#django.forms.MultiValueField) might come in handy here.

**Comment by jseppi** [comment]
I just learned about `<input type="date">` fields last week. Modern browsers will apparently show a built-in calendar widget to select dates with them. Might they be a better option than the three fields?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by jseppi** [comment]
@hbillings ^ any thoughts on that?

**Comment by toolness** [comment]
I wonder if this might also be a good question for the USWDS team?  Seems like it'd be useful to have guidance on what to do about this in the USWDS itself, since it is a good question...

**Comment by hbillings** [comment]
Good thought! They do have guidance, under "Date inputs" on this page:
https://standards.usa.gov/form-controls/ :)

IMO, three boxes helps convey exactly what format is expected. We could add
placeholder text back f MM DD YY to clarify further.


-- 
Heather Battaglia
Innovation Specialist, 18F
Chicago, IL

**Comment by jseppi** [comment]
The most compelling argument I heard about the native widget was that
people are very comfortable using date pickers, more so than entering
numbers. They also work a bit better on mobile, though I don't anyone will
be updating calc data on their phone.

Sent from my iPhone

On Aug 9, 2016, at 7:34 PM, Heather Billings <notifications@github.com>
wrote:

Good thought! They do have guidance, under "Date inputs" on this page:
https://standards.usa.gov/form-controls/ :)

IMO, three boxes helps convey exactly what format is expected. We could add
placeholder text back f MM DD YY to clarify further.


-- 
Heather Battaglia
Innovation Specialist, 18F
Chicago, IL

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/18F/calc/issues/534#issuecomment-238724500>, or mute
the thread

**Comment by toolness** [comment]
From the USWDS suggestions Heather linked to above:

> If users are trying to schedule something, a calendar picker might make more sense. Be sure to also provide an option for text entry as well.

I'm not sure if contract start/end dates are in the same contextual space as "trying to schedule something". It seems like a date picker would be especially useful for being able to, say, choose the date corresponding to "next tuesday", but it might not be useful if one knows the exact date a contract starts or ends and just wants to input it.

I'm also curious if modern browsers' native UI for `<input type="date">` includes an option for text entry or not.  If they don't, it could actually potentially be really annoying to enter a date that's e.g. 3 years and 2 months into the future!

**Comment by hbillings** [comment]
@jseppi So, lawlz, I was on my phone reading my email and didn't even see your original comment, just the mention of my handle! Sorry for the less-than-helpful reply and accidental smartassery!

I have to say I do prefer datepickers, but my understanding is that they can be tricky to make accessible. (Maybe that's why the text entry field @toolness mentioned is important?) They also don't look [super-well supported](http://caniuse.com/#feat=input-datetime). :-/

If we wanna give it a shot, though, we could potentially make use of (the min and max date settings)[https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms/The_native_form_widgets#month] to limit the range to 5 years. Maybe we could even set the second date to default to five years out?

**Comment by jseppi** [comment]
Oh ew, I didn't realize the support was so bad. I should have looked that
up before bringing them up.

I just hears about them last week and got excited, but it looks like it
might be a while before they can be used. As for accessibility, that was
one of the main selling points the speaker made about them, but I guess the
support in screen readers is probably also not great right now.

On Aug 9, 2016, at 10:14 PM, Heather Billings <notifications@github.com>
wrote:

@jseppi <https://github.com/jseppi> So, lawlz, I was on my phone reading my
email and didn't even see your original comment, just the mention of my
handle! Sorry for the less-than-helpful reply and accidental smartassery!

I have to say I do prefer datepickers, but my understanding is that they
can be tricky to make accessible. (Maybe that's why the text entry field
@toolness <https://github.com/toolness> mentioned is important?) They also
don't look super-well supported <http://caniuse.com/#feat=input-datetime>.
:-/

If we wanna give it a shot, though, we could potentially make use of (the
min and max date settings)[
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms/The_native_form_widgets#month]
to limit the range to 5 years. Maybe we could even set the second date to
default to five years out?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/18F/calc/issues/534#issuecomment-238747464>, or mute
the thread
