### ISSUE TITLE
Upload widget text should properly specify file formats

### ISSUE THREAD

**Issue by jseppi** [18F/calc#538]
<img width="683" alt="screen shot 2016-08-09 at 2 55 14 pm" src="https://cloud.githubusercontent.com/assets/697848/17529457/4a65dfde-5e41-11e6-830b-0cbf06a6841d.png">

For Schedule 70 import, as the parser is currently written, uploading a CSV won't work. The text in the upload widget is therefore misleading because only the specific S70 Excel price list will actually work.

**Comment by toolness** [comment]
Now that the user chooses their schedule in a step prior to the one where they upload a spreadsheet, we can dynamically set this value based on the schedule!  For example, since the "Fake Schedule" for development only allows CSV, we can generate the widget to only accept (and mention) CSV, while for Schedule 70 we can have it only accept and mention XLS/XLSX.
