### ISSUE TITLE
R10 Upload - Figure out how to prevent double submissions in Step 2

### ISSUE THREAD

**Issue by jseppi** [18F/calc#590]
The transition from Step 2 to Step 3 takes a long time in the R10 upload flow. It would be nice to add feedback for the user that something is happening, and figure out how to disable/hide the Submit button so that the user doesn't accidentally click it twice.

**Comment by toolness** [comment]
Hmm, so one way to do this that leverages our current tools might actually be to just turn it into an `ajaxform`, which fades out the form and assigns `pointer-events: none` so that the submit button can't be re-clicked.

I think, though, that this would warrant adding a spinner/fake-progress-bar/etc animation of some sort to the ajaxform, so that the user isn't just staring at a faded-out form for so many seconds.  This would also be useful for price lists that might be particularly large (perhaps because one of the other worksheets is big) or folks on slow internet connections.

**Comment by toolness** [comment]
Wait, is this still a major issue since we started processing bulk uploads asynchronously in #606?

That said, addressing this kind of situation still seems important for our ajaxforms in cases where the user is on a spotty internet connection.

**Comment by jseppi** [comment]
I don't think it is a major issue any more.

**Comment by jseppi** [comment]
Closing since I don't think this is an issue any more.
