### ISSUE TITLE
R10 Upload - Step 3 request times out on large data loads (on cloud.gov)

### ISSUE THREAD

**Issue by jseppi** [18F/calc#600]
When loading a large file, the request for Step 3 takes too long and cloud.gov aborts it. We apparently are unable to change the request timeout to be longer.

I think the most robust solution would be to use `celery` and spin the long-running tasks off to its processing queue. This will require also having `redis` (or similar) running in our deployment. This is also probably not trivial to get setup.

**Comment by toolness** [comment]
Ok, I've filed #606 as a quick fix that we can easily migrate to a task queue once that's set up.

Note that in July, [CM mentioned on Slack](https://18f.slack.com/archives/cloud-gov-support/p1468447621001269) that he's been using [`rq`](http://python-rq.org/) instead of Celery to great success.

Another option, especially if we want to provide live feedback on progress to the end-user, may be to use [Django Channels](https://channels.readthedocs.io/en/latest/index.html), which works with 1.8 and is made specifically for background tasks (among other things).

**Comment by jseppi** [comment]
Just looked at rq and django-rq. It does look quite easy to setup!

**Comment by toolness** [comment]
Ok, here's what I'm thinking right now.

Channels is *awesome* but it does fundamentally change the way Django handles requests. I think it basically means that all our current servers will actually become *workers* that pick up messages off redis.  HTTP requests are just another kind of "message" in channels.  We'd still need at least one gunicorn server that effectively serves as the "interface" between the HTTP protocol and the messaging layer that Django Channels uses.

That's really cool, but I have some anxieties about how this will work with cloud.gov.  Also, if redis goes down for some reason, I *think* it'd mean that our whole website would go down.

On the other hand, while I haven't looked closely at `rq` yet, I *assume* that it's just a standard task queue, and that none of our legacy code would touch it; only the region 10 bulk upload code would.  That makes it less of a risk, IMO, since we wouldn't be driving all our traffic through a stack that we're not very familiar with.

I guess as excited as I am to tinker with channels, I think `rq` is probably a safer and simpler bet for now.  And as long as we architect things in a reasonable way, it still shouldn't be too difficult to migrate to Channels in the future if we want.

Thoughts @jseppi ?

**Comment by jseppi** [comment]
Oh boy, yeah, such a large infrastructural change is probably ill-advised. I would personally feel more comfortable with `rq` I think, especially given that we have in-house experience with it.

**Comment by toolness** [comment]
Sounds good! I am now refactoring #606 to work with `rq` instead of spinning off a separate thread.

**Comment by jseppi** [comment]
Cool. I'll setup the `redis` on staging.
