### ISSUE TITLE
Default Django Admin Login page is shown for logged-in, non-staff user

### ISSUE THREAD

**Issue by jseppi** [18F/calc#670]
Just found some bizarre behavior that allows a user to get to the default Django Admin login page (the one with username and password).

Steps to reproduce:
1. Login as a non-staff user
2. Visit `/admin`
3. You will be redirected to `/admin/login/?next=/admin/`, which will show the default Admin login page.

This should be disabled because we never want password login since we are using cloud.gov's UAA provider for all authentication.

**Comment by jseppi** [comment]
cc @toolness

**Comment by jseppi** [comment]
Looks like Django 1.10 has a fix for this weird behavior (redirecting an already authenticated user back to to login page): See bullet point about `redirect_authenticated_user` at https://docs.djangoproject.com/en/dev/releases/1.10/#django-contrib-auth

**Comment by jseppi** [comment]
In `urls.py` we have

```py
# http://stackoverflow.com/a/13186337
admin.site.login = login_required(admin.site.login)
```

The linked StackOverflow answer there has a comment that describes this exact issue:
http://stackoverflow.com/questions/6779265/how-can-i-not-use-djangos-admin-login-view/13186337#comment44407825_13186337

**Comment by toolness** [comment]
Just wanted to note that this issue doesn't actually affect the *security* of our site, though it does affect its usability.  Because we've disabled `django.contrib.auth.backends.ModelBackend`, there's no way a user can log in via a password; that is, entering a valid username/password combination into an accidentally-exposed django-admin login page will still fail.
