### ISSUE TITLE
Bulk Upload: Step 3 405 just shows a blank page

### ISSUE THREAD

**Issue by hbillings** [18F/calc#721]
I let my session time out between steps 2 and 3, hit the button to continue in step 2, was redirected to the login page, logged in, and then was redirected to Step 3. But I got a 405 and a completely blank page. Seems like we could handle that error better?

**Comment by jseppi** [comment]
Huh, definitely should handle it better.

For future readers, since I had to look up what a `405` error is - it is "Method Not Allowed."

Bulk Upload's Step 3 only allows `POST` requests. When the user gets thrown back to the login flow and successfully authenticates, Django's login system redirects the user back to the page they were trying to view. So on Bulk Upload Step 3, it is sending a `GET` to that `POST`-only view.

**Comment by jseppi** [comment]
Hrm, maybe that flow should be slightly reorganized so that step 2 receives the `POST` (and shows the form when `GET`), and step 3 is just the success page (accessible via `GET`).

**Comment by toolness** [comment]
Yeah, that seems more in-line w/ the way our price list upload thingy works too!
