### ISSUE TITLE
Run tests not in DEBUG mode

### ISSUE THREAD

**Issue by jseppi** [18F/calc#777]
Best practices seem to involve not running tests with `DEBUG=True`. I especially think we shouldn't run our Travis builds with `DEBUG` set.

Ref discussion in https://github.com/18F/calc/pull/774#issuecomment-248442310

**Comment by toolness** [comment]
[Here's the relevant Slack discussion](https://18f.slack.com/archives/django/p1470867503000096).  I guess it does stop short of claiming that testing with `DEBUG=False` is a *best practice*, but it does seem to encourage it.

**Comment by toolness** [comment]
So one funky thing is that Django's own test framework actually *does* run tests with `DEBUG=False`, but when our `settings.py` is first loaded, `DEBUG` is usually `True`, so conditional settings in that file that query `DEBUG` are often set to their debug-ish values. This can result in weird improper configurations like https://github.com/18F/cg-django-uaa/issues/18.

Hmm, so that said, we do have this `is_running_tests()` function in our `settings.py` that we can use... I guess we could look at that at the very beginning, and force `DEBUG` to `False` if we're running tests.  I think we might still have to set certain values like our `STATICFILES_STORAGE` to be debug-ish but I'm not sure... blah.

**Comment by hbillings** [comment]
Does this apply now that we're not on Travis any more?

**Comment by toolness** [comment]
It does still apply, but ehhh I don't think it's that big a deal for transition, given all the other stuff we want to do.
