### ISSUE TITLE
Restyle errors to be clearer

### ISSUE THREAD

**Issue by hbillings** [18F/calc#779]
Currently, errors are kind of janky:
<img width="219" alt="screen shot 2016-09-21 at 10 11 16 am" src="https://cloud.githubusercontent.com/assets/509309/18717114/8c64757a-7fe4-11e6-8cf7-16dd9798d591.png">

It would be clearer if errors encapsulated the full form field, perhaps like this:
<img width="276" alt="screen shot 2016-09-21 at 10 15 35 am" src="https://cloud.githubusercontent.com/assets/509309/18717329/21ee4ff8-7fe5-11e6-8493-6204d7f713d1.png">

We should probably also change the text for screenreaders to indicate that it's "the field below" that has issues.

**Comment by toolness** [comment]
Nice!

Actually, for screenreaders we should ideally [use `aria-describedby`](https://github.com/18F/calc/issues/576).  That way the error is announced whenever the user focuses on the field--otherwise it will actually be kinda hard to hear the error, which is a bummer.  But even more annoying is that due to the way django's form framework works, implementing this is actually kind of annoying. 😞
