### ISSUE TITLE
Investigate failing selenium tests

### ISSUE THREAD

**Issue by jseppi** [18F/calc#813]
* `FunctionalTests.test_query_type_matches_exact`
* `FunctionalTests.test_query_type_matches_phrase`

**Comment by jseppi** [comment]
Very likely related to missing query_type radio buttons on the front page of CALC

<img width="507" alt="screen shot 2016-09-27 at 3 14 50 pm" src="https://cloud.githubusercontent.com/assets/697848/18892034/2a15e896-84c5-11e6-9497-e73aa1c641f8.png">

**Comment by toolness** [comment]
I'm looking into this now!  It does indeed appear as though our selenium tests (specifically `set_form_value`) are assuming that the `<input type="radio">` it's clicking on is actually visible, and throwing an exception if not.  Because the USWDS radios work by hiding those actual `<input>`s and using the `<label>`s as proxies, selenium is having a fit.

I think I will probably fix this by having selenium click on the label instead of the radio. We'll see if that works!
