### ISSUE TITLE
Get a deployment review by an expert cloud.gov/cloud foundry engineer

### ISSUE THREAD

**Issue by jseppi** [18F/calc#875]
Specific things we need help with:

- General review of practices, manifests, resource sizing, etc.
- Zero-downtime deploys
  - manual blue-green deploys or cf-autopilot?
- Possible manifest inheritance
- Proper way to migrate production database during deployment
- What to do about rqworker and rqschedule instances
  - have both `a` and `b` versions of each (like we do currently, but that probably won't work as I intended)
- ~~Figure out this weird `panic: send on closed channel` error when attempting to push all 3 apps: https://github.com/18F/calc/issues/877~~ upgrading `cf-cli` fixes it

**Comment by jseppi** [comment]
@toolness: feel free to clarify/modify/addify to the list of topics in the root comment

**Comment by rogeruiz** [comment]
Here are some recommendations. I would also ping in #cloud-gov-support for any other opinions.

> General review of practices, manifests, resource sizing, etc.

This is something that I would say falls on the specific needs for your application. You can run the `cf org <ORG_NAME>` to get information about the memory size available for you across all the spaces in the organization. Keep in mind that things like zero-downtime deployments eat into double the amount of resources during the deployment because two exact instances of your application are built. So two instances at 1G each will consume 4G total when performing a zero-downtime deployment.

> Zero-downtime deploys
> manual blue-green deploys or cf-autopilot

I recommend using `cf-autopilot` based on anecdotal evidence that it works better. It also enforces having `manifest.yml` files as they're required to use it. When using this plugin, your CI server will need to install it before it deploys your code.

> Possible manifest inheritance

Since manifests are configuration, I would go against inheritance as there is no way to override properties inherited from an earlier manifest. This is especially important for routes. So I would be careful not to inherit any route properties across your manifests. Also, any property that can be declared within an `application` stanza can be declared outside of it in the manifest file. This allows for inheritance within a single manifest file.

> Proper way to migrate production database during deployment

Super tricky subject. Migrations that may adversely affect your current application should be tested on in staging to avoid issues like that. Because spaces share bound service between instances of the same application, you may want to look into binding a new service temporarily to the application and migrating data between them and shutting the other service and application down. This would be a complicated process though that I would avoid unless the migrations absolutely needed to be automated with zero-downtime. For DB migrations, nothing beats a clear documented guide and SLA for database migrations which could always inadvertently cause the application to crash.

> What to do about rqworker and rqschedule instances
have both a and b versions of each (like we do currently, but that probably won't work as I intended)

I'm not sure how to answer this.

**Comment by jseppi** [comment]
@rogeruiz: would you mind taking a look at #885 to see if what I did looks 👍 ?

**Comment by jseppi** [comment]
This is done, just neglected to close the issue.
