### ISSUE TITLE
Add /healthcheck check to New Relic

### ISSUE THREAD

**Issue by jseppi** [18F/calc#878]
After our new CALC is deployed, we should monitor `/healthcheck` with New Relic

**Comment by toolness** [comment]
This seems related to #1199.

Since we only have access to New Relic Synthetics Lite right now, that means we can only create Ping monitors.

One unclear thing about Ping monitors is whether they actually check the HTTP response code of the endpoint; I wrote the `/healthcheck` code to return a 200 if everything was OK and a 500 if anything was amiss, but I'm not sure if the New Relic Ping monitor will actually fail if it gets a 500. 

So I made a [Ping monitor](https://synthetics.newrelic.com/accounts/987071/monitors/facaac62-136f-4ec6-96e3-af49c48090b9) that specifically looks for the text `"is_database_synchronized": true`, in the response, since that's currently the only thing that's really being tested by that endpoint... But we might want to add another key called `"is_everything_ok"` that basically tells us whether _all_ the checks pass, so that even if New Relic ignores 500s, it will still fail if it doesn't find that text.

**Comment by jseppi** [comment]
I am pretty sure New Relic ping monitors will fail for non-ok responses. That's how I found out that the api was returning `403`s on Friday.

**Comment by toolness** [comment]
Awesome! In that case, I guess it should be OK to close this issue?  Though if you could review my ping monitor (linked to in my last comment) to make sure it seems legit, that'd help too.

**Comment by jseppi** [comment]
Looks good to me, thanks! I did, however, modify it to add additional US ping locations.
