### ISSUE TITLE
Step 3 Errors button placement

### ISSUE THREAD

**Issue by jseppi** [18F/calc#894]
I was taking a look at the Step 3 Errors page and it felt like the action buttons were a little disjointed from their corresponding page elements, so I fired up the ole pixlr.com and did some cowboy cut-n-pasting:

![error_step](https://cloud.githubusercontent.com/assets/697848/19177144/f829bec2-8c0b-11e6-9713-7639f7fa91e5.png)

The cancel link placement is kinda meh, but what do you think about moving the other buttons around, @hbillings?

**Comment by ericronne** [comment]
Is this resolved with #1245, @jseppi?

**Comment by jseppi** [comment]
I don't think #1245 addresses the button placement at all

**Comment by ericronne** [comment]
doh, sry

this feature let's the user cancel the upload and start over?
if so, is there a modal warning?

**Comment by jseppi** [comment]
No, this issue is about moving the "Continue without these rows" up above the upload widget, so that the "Upload revised price list" button is more "connected" with the upload widget.

**Comment by jseppi** [comment]
but to answer your question about Canceling an upload, yes, there is a modal dialog that is shown

**Comment by ericronne** [comment]
Here's my proposed layout. I changed "Want to try that again?" to "Upload a replacement price list," both for clarity and because the phrasing sounded more colloquial / less "functional" than the rest of the site copy. Agree?

The gray caption text would include an anchor link, to bump the user down to the upload widget on the same page. I'm not sure if this style has yet been implemented. If not, i can do a simpler verison.

![upload-03b-errors-v2](https://cloud.githubusercontent.com/assets/9259185/22438233/d4f4efc2-e6f0-11e6-9b40-970e7a71877b.png)

**Comment by ericronne** [comment]
cc @hbillings

**Comment by hbillings** [comment]
While I agree the phrasing is clearer, I do like having it as a question or otherwise making it clear that uploading a replacement is completely optional. (also we prolly wanna change the caption on the replacement list upload to not mention "rows below")

**Comment by ericronne** [comment]
Made mods incorporating @hbillings wise counsel …
 - Changed the error text in order to relocate the anchor link to that higher-profile location
 - This opens up the gray caption for us to further describe the consequences of "continuing anyway" (can kill this if we don't think it's needed)
 - Tried a warning triangle on the "continue anyway" button (if this proves useful, we should make it the pattern for this sort of button)
 - Added ", if desired" to the second-section header, and updated the text below it because i don't read things

![upload-03b-errors-v2](https://cloud.githubusercontent.com/assets/9259185/22440674/2f31b020-e6fa-11e6-9d6b-be7959935838.png)
