### ISSUE TITLE
More specific search terms result in less specific autocomplete suggestions

### ISSUE THREAD

**Issue by hbillings** [18F/calc#948]
So say I want to search for senior electrical engineers. If I start with "electric," I get this (a bit down the list of suggestions):
<img width="628" alt="screen shot 2016-10-19 at 9 22 00 am" src="https://cloud.githubusercontent.com/assets/509309/19522675/a90d48e6-95dd-11e6-8f54-2384259be643.png">

But if I type in the full title of what I want, those suggestions are nowhere to be found, and instead I get this:
<img width="640" alt="screen shot 2016-10-19 at 9 22 19 am" src="https://cloud.githubusercontent.com/assets/509309/19522691/bdff79ae-95dd-11e6-830c-2b4a049478d0.png">

**Comment by toolness** [comment]
Are you doing this search on calc.gsa.gov?  I think that this was actually reported back in july as #458 and fixed in #477, but because we haven't gotten the ATO yet, we haven't been able to push the fix to calc.gsa.gov 😞

**Comment by hbillings** [comment]
sadnesssss. I could test this locally to make sure it works, assuming the `load_data` command loads all the R10 data and not just the sampling that's on staging?

**Comment by jseppi** [comment]
Yep, `load_data` will load it all

**Comment by toolness** [comment]
I am pretty sure this was fixed by #477, and is now in production on calc.gsa.gov:

<img width="724" alt="screen shot 2017-01-11 at 7 42 06 am" src="https://cloud.githubusercontent.com/assets/124687/21849006/869c828c-d7d1-11e6-92e9-2e276d393bf2.png">

I'm closing this now, but feel free to re-open if you disagree @hbillings !
