### ISSUE TITLE
Admin view - confusing duplicated status/current status

### ISSUE THREAD

**Issue by jseppi** [18F/calc#974]
<img width="475" alt="screen shot 2016-10-27 at 10 10 43 am" src="https://cloud.githubusercontent.com/assets/697848/19773141/0d95c1ac-9c2e-11e6-9024-cc95c14cd3ca.png">

Maybe we could show the `This price list is not currently approved, so its data is not in CALC. To approve it, you will need to use the 'Approve selected price lists' action from the list view.` message in the same line as the "Status:", and remove "Current status:" altogether?

thoughts, @toolness?

**Comment by toolness** [comment]
That sounds good, though I think it'd still be useful to provide the short name of the status, so that they know how it correlates to the "status" field in the other views, if that makes sense. Almost like if you just moved the descriptive text underneath the value of the "status" field, so that it sort of serves as a kind of tooltip or context-specific help text?

**Comment by jseppi** [comment]
Yup, that's what I was suggesting, basically:

```
Status: new
        This price list is not currently approved, so its data is not in CALC. To approve it, you will need to use the 'Approve selected price lists' action from the list view.
```

**Comment by toolness** [comment]
Yassss 💥 💯 🇺🇸
