### ISSUE TITLE
Valid rows in price list detail don't reflect changes made via admin UI

### ISSUE THREAD

**Issue by toolness** [18F/calc#993]
It looks like the admin view for changing unapproved price lists (e.g. `/admin/data_capture/unapprovedpricelist/4/`) allows data admins to view and edit "submitted price list rows".  However, changing this information doesn't reflect any changes on the "Valid price list rows" section of the price list detail page (e.g. `/data-capture/price-lists/4`).

I *think* this is because the admin UI is presenting `SubmittedPriceListRow` models, while the price list detail page is presenting the deserialization of `SubmittedPriceList.serialized_gleaned_data`. While these start out identical, the former could be changed by data admins.

In any case, this could be confusing to data admins and COs.

**Comment by jseppi** [comment]
Hrm, yeah, I totally missed that situation.

I suppose the best fix would be to use the `SubmittedPriceListRow` models for the "Valid price list rows" table and use the `serialized_gleaned_data` for the error rows. Or maybe it makes sense to not show the error rows at all?

**Comment by toolness** [comment]
Hmm I like the idea of showing the error rows, possibly hidden behind an `<expandable-area>`--that would also make it easy for data administrators to see the error information if they wanted, since it's not currently visible in the admin UI (just filed #995 to make it easy to go from one to the other).

**Comment by jseppi** [comment]
Ah, I kinda remember why I went with `gleaned_data` instead of using `SubmittedPriceListRows` in the first place. It is because with `gleaned_data` we have access to `to_table`, which is slightly different depending on the chosen schedule.

It's not a problem per se to use `SubmittedPriceListRows`, but the table will be a bit different from what the user had seen in Step 4 of the Price List Upload flow, since the rows will be normalized to the `SubmittedPriceListRows` model instead of showing the gleaned columns and original names.

**Comment by jseppi** [comment]
busting this up real quick
